### ISSUE TITLE
806756665 - Dunk Hitless Any% Seed

### ISSUE THREAD

**Issue by Shortman422** [acidflow-noita/noitamap#34]
Only Main world capture for seed `806756665`

Label: `new-map-capture` requested but I lack permissions to add.

https://drive.google.com/file/d/1ojP8Tc-mSCyx-W384pThaYa05NtDMQW7/view

File was named `new-game-main-branch-middle-2024-04-30-806756665.dzi` instead of `regular-main-branch-middle-2024-04-30-806756665.dzi` on accident.

**Comment by Shortman422** [comment]
I did have the 60 frame setting and I see the entities in my `C:\Program Files (x86)\Steam\steamapps\common\Noita\mods\noita-mapcap\output` folder.

Map Capture Settings: https://drive.google.com/file/d/1pgDBaizfwzYIgWxg6TAuUSfMcEUoJ-6v/view
Entities in `0,0.png`: https://drive.google.com/file/d/1QssVoqhe4kQrfMBl-b0twpSKzJm2KmjJ/view

I suspect the error is related to the failed to load entities/player when stitching?
```
.\stitch.exe --output new-game-main-branch-middle-2024-04-30-806756665.dzi --blend-tile-limit 1 --dzi-tile-size 512 --xmin -17920 --xmax 18432 --ymin -31744 --ymax 41984 --webp-level 9
```
```
2024/07/15 03:11:31 Noita MapCapture stitching tool v2.23.0.
2024/07/15 03:11:31 Failed to load entities: open ..\..\output\entities.json: The system cannot find the file specified..
2024/07/15 03:11:31 Failed to load player path: open ..\..\output\player-path.json: The system cannot find the file specified..
2024/07/15 03:11:31 Starting to read tile information at "..\\..\\output".
2024/07/15 03:11:44 Got 2592 tiles.
2024/07/15 03:11:44 Total size of the possible output space is (-18432,-31744)-(18432,41984).
2024/07/15 03:11:44 Creating DZI descriptor "new-game-main-branch-middle-2024-04-30-806756665.dzi".
2024/07/15 03:11:44 Creating DZI tiles in "new-game-main-branch-middle-2024-04-30-806756665_files".
13704 / 13704 [----------------------------------------------------------------------------------------------------------------------------------------] 100.00% 3 p/s 1h29m5s
2024/07/15 04:40:49 Created output in 1h29m5.4794822s.
```

Perhaps related to error displayed for map capture with `enableModDetection` in `processMemory`: https://drive.google.com/file/d/1XcQ9xe2nwG-WFXUM6IsWfEVFz2J2z4Bk/view
I was hoping this was just because of epilogue 2 update but I am on the 2024-04-30 release steam build (not beta).

**Comment by Dadido3** [comment]
Hi,

`Failed to load entities` is only used when you want to render overlay boxes for entities in the stitching process. Similarly the `Failed to load player path` error is only relevant if you want to render the path the player has taken in a playthrough. So both errors just mean that the stitcher will not render these additional things, and only output a clean stitch without any additional stuff.

Also, the `enableModDetection` error is only relevant if you need Noita to generate some secret stuff on the map (Which is normally hidden when you have any mods enabled). I'll update the mapcap mod in the future, so it will work with newer versions.

The real problem still seems to be that the map is captured faster than Noita can generate and populate it. This can be seen in this part of your map capture:
![grafik](https://github.com/user-attachments/assets/03ea2251-508f-4e86-80fd-b3c1104155d6)

Normally there would be at least one or two mobs, one of which caused Dunk's hitless attempts to end prematurely because he always bumped into him.

Your capture contains some mobs, but not all. And for the same reason there are not fully rendered chunks, or missing/not fully populated formations in your capture.

Unfortunately there is no easy fix that i know right now. You probably need to increase the capture delay even further (Which can't be done without modifications to the mod). But it's probably not worth the effort.

**Comment by Shortman422** [comment]
Thanks for explaining. It sounds like tuning the frame setting over time and use would optimize for the local system. I did notice that most mobs/liquids would appear before hitting 60 frames and would sometimes flicker on frame 60. The frame counter would also go as high as 90 and then quadrants of the game would flicker. I noticed a few of these in the parallel world cursed rock areas like in [16384,-14336.png](https://drive.google.com/file/d/1ZIgenGoSuMGCOQgI70CtHFN5GAVl8LB-/view).

Great job with the tools!
